# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
