# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0002_alimama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentId', models.CharField(max_length=20, unique=True, verbose_name='代理广告位')),
                ('AgentName', models.CharField(default='', max_length=20, verbose_name='代理名称')),
            ],
        ),
        migrations.CreateModel(
            name='AliConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentName', models.CharField(default='', max_length=20, verbose_name='代理名称')),
                ('AgentUpName', models.CharField(blank=True, max_length=20, verbose_name='上线名称')),
                ('AgentPerc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='自获佣金比例')),
                ('Agent2rdPerc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='提取二级佣金比例')),
                ('Agent3rdPerc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='提取三级佣金比例')),
                ('ZhaohuoPid', models.CharField(blank=True, default='', max_length=20, verbose_name='找货广告位')),
                ('ZhaohuoName', models.CharField(blank=True, default='', max_length=20, verbose_name='找货名称')),
                ('ZhaohuoPerc', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='找货佣金比例')),
                ('ZhaohuoBot', models.CharField(blank=True, default='', max_length=20, verbose_name='找货机器人')),
                ('GroupId', models.CharField(blank=True, default='', max_length=20, verbose_name='团队合伙人')),
                ('TopLevel', models.BooleanField(default='', verbose_name='顶级账号')),
                ('Active', models.BooleanField(default='', verbose_name='激活状态')),
                ('ValidBegin', models.DateField(blank=True, null=True, verbose_name='有效期开始时间')),
                ('ValidEnd', models.DateField(blank=True, null=True, verbose_name='有效期结束时间')),
                ('AgentId', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AId', to='disk.Agent')),
                ('AgentUpId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AUpId', to='disk.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='AliOrd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatDate', models.DateTimeField(default='', verbose_name='创建时间')),
                ('ClickDate', models.DateTimeField(default='', verbose_name='点击时间')),
                ('CommType', models.CharField(default='', max_length=20, verbose_name='商品信息')),
                ('CommId', models.CharField(default='', max_length=20, verbose_name='商品ID')),
                ('WangWangId', models.CharField(default='', max_length=20, verbose_name='掌柜旺旺')),
                ('StoreId', models.CharField(default='', max_length=20, verbose_name='所属店铺')),
                ('CommQty', models.CharField(default='', max_length=20, verbose_name='商品数')),
                ('CommPrice', models.CharField(default='', max_length=20, verbose_name='商品单价')),
                ('OrdStatus', models.CharField(default='', max_length=20, verbose_name='订单状态')),
                ('OrdType', models.CharField(default='', max_length=20, verbose_name='订单类型')),
                ('IncomePerc', models.CharField(default='', max_length=8, verbose_name='收入比率')),
                ('DividePerc', models.CharField(default='', max_length=8, verbose_name='分成比率')),
                ('PayAmount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='付款金额')),
                ('EstAmount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='预估效果')),
                ('SettleAmt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='结算金额')),
                ('EstIncome', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='预估收入')),
                ('SettleDate', models.CharField(default='', max_length=20, verbose_name='结算时间')),
                ('RebatePerc', models.CharField(default='', max_length=8, verbose_name='佣金比例')),
                ('RebateAmt', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='佣金金额')),
                ('AllowancePerc', models.CharField(default='', max_length=8, verbose_name='补贴比例')),
                ('AllowanceAmt', models.CharField(default='', max_length=8, verbose_name='补贴金额')),
                ('AllowanceType', models.CharField(default='', max_length=20, verbose_name='补贴类型')),
                ('Platform', models.CharField(default='', max_length=20, verbose_name='成交平台')),
                ('ThirdParty', models.CharField(default='', max_length=20, verbose_name='第三方服务')),
                ('OrderId', models.CharField(default='', max_length=20, verbose_name='订单编号')),
                ('Category', models.CharField(default='', max_length=20, verbose_name='类目名称')),
                ('MediaId', models.CharField(default='', max_length=20, verbose_name='来源媒体ID')),
                ('MediaName', models.CharField(default='', max_length=20, verbose_name='来源媒体名称')),
                ('PosID', models.CharField(default='', max_length=20, verbose_name='广告位ID')),
                ('PosName', models.CharField(default='', max_length=20, verbose_name='广告位名称')),
                ('UplineId', models.CharField(blank=True, max_length=20, verbose_name='上线ID')),
                ('UplineName', models.CharField(blank=True, max_length=20, verbose_name='上线名称')),
                ('Up2lineId', models.CharField(blank=True, max_length=20, verbose_name='上上线ID')),
                ('Up2lineName', models.CharField(blank=True, max_length=20, verbose_name='上上线名称')),
                ('IncomePercSelf', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='自获佣金比例')),
                ('SharePercUp1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='贡献上级佣金比例')),
                ('SharePercUp2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='贡献上上级佣金比例')),
                ('IncomeSelf', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='自获佣金额')),
                ('ShareUp1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='贡献上级佣金额')),
                ('ShareUp2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='贡献上上级佣金额')),
            ],
        ),
        migrations.DeleteModel(
            name='Alimama',
        ),
    ]
