# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0002_alimama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimama',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='结算佣金'),
        ),
        migrations.AlterField(
            model_name='alimama',
            name='pid',
            field=models.CharField(max_length=30, verbose_name='推广位'),
        ),
    ]
