# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0003_auto_20170730_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliord',
            name='IncomePercSelf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='自获佣金比例'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='SharePercUp1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='贡献上级佣金比例'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='SharePercUp2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='贡献上上级佣金比例'),
        ),
    ]
