# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0004_auto_20170730_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliconfig',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
