# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0004_auto_20170720_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimama',
            name='order',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
    ]
