# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0005_aliconfig_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentName',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='代理名称'),
        ),
    ]
