# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0006_auto_20170720_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliord',
            name='AllowanceAmt',
            field=models.CharField(default='', max_length=20, verbose_name='补贴金额'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='AllowancePerc',
            field=models.CharField(default='', max_length=20, verbose_name='补贴比例'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='AllowanceType',
            field=models.CharField(default='', max_length=20, verbose_name='补贴类型'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='Category',
            field=models.CharField(default='', max_length=20, verbose_name='类目名称'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='ClickDate',
            field=models.CharField(default='', max_length=20, verbose_name='点击时间'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='CommId',
            field=models.CharField(default='', max_length=20, verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='CommPrice',
            field=models.CharField(default='', max_length=20, verbose_name='商品单价'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='CommQty',
            field=models.CharField(default='', max_length=20, verbose_name='商品数'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='CommType',
            field=models.CharField(default='', max_length=20, verbose_name='商品信息'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='CreatDate',
            field=models.CharField(default='', max_length=20, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='DividePerc',
            field=models.CharField(default='', max_length=20, verbose_name='分成比率'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='EstAmount',
            field=models.CharField(default='', max_length=20, verbose_name='预估效果'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='EstIncome',
            field=models.CharField(default='', max_length=20, verbose_name='预估收入'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='IncomePerc',
            field=models.CharField(default='', max_length=20, verbose_name='收入比率'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='MediaId',
            field=models.CharField(default='', max_length=20, verbose_name='来源媒体ID'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='MediaName',
            field=models.CharField(default='', max_length=20, verbose_name='来源媒体名称'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='OrdStatus',
            field=models.CharField(default='', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='OrdType',
            field=models.CharField(default='', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='OrderId',
            field=models.CharField(default='', max_length=20, verbose_name='订单编号'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='PayAmount',
            field=models.CharField(default='', max_length=20, verbose_name='付款金额'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='Platform',
            field=models.CharField(default='', max_length=20, verbose_name='成交平台'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='PosID',
            field=models.CharField(default='', max_length=20, verbose_name='广告位ID'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='PosName',
            field=models.CharField(default='', max_length=20, verbose_name='广告位名称'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='RebateAmt',
            field=models.CharField(default='', max_length=20, verbose_name='佣金金额'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='RebatePerc',
            field=models.CharField(default='', max_length=20, verbose_name='佣金比例'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='SettleAmt',
            field=models.CharField(default='', max_length=20, verbose_name='结算金额'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='SettleDate',
            field=models.CharField(default='', max_length=20, verbose_name='结算时间'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='StoreId',
            field=models.CharField(default='', max_length=20, verbose_name='所属店铺'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='ThirdParty',
            field=models.CharField(default='', max_length=20, verbose_name='第三方服务'),
        ),
        migrations.AddField(
            model_name='aliord',
            name='WangWangId',
            field=models.CharField(default='', max_length=20, verbose_name='掌柜旺旺'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='结算佣金2'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='order',
            field=models.CharField(max_length=20, verbose_name='订单编号2'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='pid',
            field=models.CharField(max_length=30, verbose_name='推广位2'),
        ),
    ]
