# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0007_auto_20170720_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliord',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='aliord',
            name='order',
        ),
        migrations.RemoveField(
            model_name='aliord',
            name='pid',
        ),
    ]
