# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0007_auto_20170806_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliord',
            name='PosName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='广告位名称'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='Up2lineId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上上线ID'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='Up2lineName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上上线名称'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='UplineId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上线ID'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='UplineName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上线名称'),
        ),
    ]
