# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0008_auto_20170807_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='Active',
            field=models.BooleanField(default=False, verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='TopLevel',
            field=models.BooleanField(default=False, verbose_name='顶级账号'),
        ),
    ]
