# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0009_auto_20170720_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgendId', models.CharField(default='', max_length=20, verbose_name='代理ID')),
                ('AgentName', models.CharField(default='', max_length=20, verbose_name='代理名称')),
                ('AgentPID', models.CharField(default='', max_length=20, verbose_name='代理PID')),
                ('AgentPerc', models.DecimalField(decimal_places=2, default='', max_digits=3, verbose_name='自获佣金比例')),
                ('Agent2rdPerc', models.DecimalField(decimal_places=2, default='', max_digits=3, verbose_name='提取二级佣金比例')),
                ('Agent3rdPerc', models.DecimalField(decimal_places=2, default='', max_digits=3, verbose_name='提取三级佣金比例')),
                ('ZhaohuoName', models.CharField(default='', max_length=20, verbose_name='找货名称')),
                ('ZhaohuoPid', models.CharField(default='', max_length=20, verbose_name='找货PID')),
                ('ZhaohuoPerc', models.CharField(default='', max_length=20, verbose_name='找货佣金比例')),
                ('ZhaohuoBot', models.CharField(default='', max_length=20, verbose_name='找货机器人')),
                ('GroupId', models.CharField(default='', max_length=20, verbose_name='团队合伙人')),
                ('TopLevel', models.CharField(default='', max_length=20, verbose_name='顶级账号')),
                ('Active', models.BooleanField(default='', verbose_name='激活状态')),
                ('ValidBegin', models.DateField(default='', verbose_name='有效期开始时间')),
                ('ValidEnd', models.DateField(default='', verbose_name='有效期结束时间')),
            ],
        ),
        migrations.AlterField(
            model_name='aliord',
            name='AllowanceAmt',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='补贴金额'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='AllowancePerc',
            field=models.DecimalField(decimal_places=4, default='', max_digits=5, verbose_name='补贴比例'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='DividePerc',
            field=models.DecimalField(decimal_places=2, default='', max_digits=3, verbose_name='分成比率'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='EstAmount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='预估效果'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='EstIncome',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='预估收入'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='IncomePerc',
            field=models.DecimalField(decimal_places=4, default='', max_digits=5, verbose_name='收入比率'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='PayAmount',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='付款金额'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='RebateAmt',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='佣金金额'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='RebatePerc',
            field=models.DecimalField(decimal_places=4, default='', max_digits=5, verbose_name='佣金比例'),
        ),
        migrations.AlterField(
            model_name='aliord',
            name='SettleAmt',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, verbose_name='结算金额'),
        ),
    ]
