# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0010_auto_20170814_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentId', models.CharField(blank=True, max_length=20, null=True, verbose_name='代理ID')),
                ('AgentName', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='代理名称')),
                ('AgentUpId', models.CharField(blank=True, max_length=20, null=True, verbose_name='上线ID')),
                ('AgentUpName', models.CharField(blank=True, max_length=20, verbose_name='上线名称')),
                ('AgentPerc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='自获佣金比例')),
                ('Agent2rdPerc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='提取二级佣金比例')),
                ('Agent3rdPerc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='提取三级佣金比例')),
                ('ZhaohuoPid', models.CharField(blank=True, default='', max_length=20, verbose_name='找货广告位')),
                ('ZhaohuoName', models.CharField(blank=True, default='', max_length=20, verbose_name='找货名称')),
                ('ZhaohuoPerc', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='找货佣金比例')),
                ('ZhaohuoBot', models.CharField(blank=True, default='', max_length=20, verbose_name='找货机器人')),
                ('GroupId', models.CharField(blank=True, default='', max_length=20, verbose_name='团队合伙人')),
                ('IncomeSelf', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='自获佣金额')),
                ('IncomeLv1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='下级贡献佣金')),
                ('IncomeLv2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='二级贡献佣金')),
                ('IncomeTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='总佣金')),
                ('CalculateStatus', models.CharField(blank=True, default='', max_length=10, verbose_name='计算状态')),
                ('CalculateYear', models.CharField(blank=True, default='', max_length=4, verbose_name='计算年份')),
                ('CalculateMonth', models.CharField(blank=True, default='', max_length=2, verbose_name='计算月份')),
                ('PayAccount', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付账号')),
                ('PayStatus', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付情况')),
                ('Slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '工资记录',
                'verbose_name': '工资记录',
            },
        ),
    ]
