# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0011_auto_20170721_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliconfig',
            name='AgendId',
        ),
        migrations.RemoveField(
            model_name='aliconfig',
            name='AgentPID',
        ),
        migrations.AddField(
            model_name='aliconfig',
            name='AgentId',
            field=models.CharField(default='', max_length=20, verbose_name='代理广告位'),
        ),
        migrations.AddField(
            model_name='aliconfig',
            name='AgentUpId',
            field=models.CharField(default='', max_length=20, verbose_name='上线广告位'),
        ),
        migrations.AddField(
            model_name='aliconfig',
            name='AgentUpName',
            field=models.CharField(default='', max_length=20, verbose_name='上线名称'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoPid',
            field=models.CharField(default='', max_length=20, verbose_name='找货广告位'),
        ),
    ]
