# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0011_payresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': '代理', 'verbose_name_plural': '代理'},
        ),
        migrations.AlterModelOptions(
            name='aliconfig',
            options={'verbose_name': '代理配置', 'verbose_name_plural': '代理配置'},
        ),
        migrations.AlterModelOptions(
            name='aliord',
            options={'verbose_name': '推广订单', 'verbose_name_plural': '推广订单'},
        ),
        migrations.AlterField(
            model_name='payresult',
            name='Agent2rdPerc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='提取二级佣金比例'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='Agent3rdPerc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='提取三级佣金比例'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='AgentPerc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='自获佣金比例'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='CalculateMonth',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='计算月份'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='CalculateStatus',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='计算状态'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='CalculateYear',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='计算年份'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='GroupId',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='团队合伙人'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='ZhaohuoBot',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='找货机器人'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='ZhaohuoName',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='找货名称'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='ZhaohuoPid',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='找货广告位'),
        ),
    ]
