# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0012_auto_20170721_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentUpId',
            field=models.CharField(max_length=20, verbose_name='上线广告位'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentUpName',
            field=models.CharField(max_length=20, verbose_name='上线名称'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoPerc',
            field=models.DecimalField(decimal_places=2, default='', max_digits=3, verbose_name='找货佣金比例'),
        ),
    ]
