# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0012_auto_20171121_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payresult',
            name='GroupId',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='组号'),
        ),
    ]
