# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0013_auto_20170721_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentUpId',
            field=models.CharField(blank=True, max_length=20, verbose_name='上线广告位'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentUpName',
            field=models.CharField(blank=True, max_length=20, verbose_name='上线名称'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='GroupId',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='团队合伙人'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='TopLevel',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='顶级账号'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ValidBegin',
            field=models.DateField(blank=True, default='', verbose_name='有效期开始时间'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ValidEnd',
            field=models.DateField(blank=True, default='', verbose_name='有效期结束时间'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoBot',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='找货机器人'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoName',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='找货名称'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoPid',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='找货广告位'),
        ),
    ]
