# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0014_auto_20170721_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoPerc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, verbose_name='找货佣金比例'),
        ),
    ]
