# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0015_auto_20170727_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='ValidBegin',
            field=models.DateField(blank=True, verbose_name='有效期开始时间'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='ValidEnd',
            field=models.DateField(blank=True, verbose_name='有效期结束时间'),
        ),
    ]
