# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0016_auto_20170727_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliconfig',
            name='ZhaohuoPerc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='找货佣金比例'),
        ),
    ]
