# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0017_auto_20171207_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliconfig',
            name='AppName',
        ),
        migrations.RemoveField(
            model_name='aliconfig',
            name='AppPid',
        ),
        migrations.RemoveField(
            model_name='aliconfig',
            name='ZhaohuoName',
        ),
        migrations.RemoveField(
            model_name='aliconfig',
            name='ZhaohuoPid',
        ),
    ]
