# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0018_auto_20170727_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentId', models.CharField(max_length=20, unique=True, verbose_name='代理广告位')),
                ('AgentName', models.CharField(default='', max_length=20, verbose_name='代理名称')),
            ],
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentId',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aid', to='disk.Agent'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentUpId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bId', to='disk.Agent'),
        ),
    ]
