# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0019_auto_20171207_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='payresult',
            name='AppName',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='APP广告位名称'),
        ),
        migrations.AddField(
            model_name='payresult',
            name='AppPid',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='APP广告位'),
        ),
        migrations.AlterField(
            model_name='aliconfig',
            name='AgentUpId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AUpId', to='disk.Agent', verbose_name='上线'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='ZhaohuoName',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='找货名称'),
        ),
        migrations.AlterField(
            model_name='payresult',
            name='ZhaohuoPid',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='找货广告位'),
        ),
    ]
