# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0023_auto_20171222_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliord',
            name='IncomeAgent',
        ),
        migrations.RemoveField(
            model_name='aliord',
            name='IncomeApp',
        ),
        migrations.RemoveField(
            model_name='aliord',
            name='IncomeJD',
        ),
        migrations.RemoveField(
            model_name='aliord',
            name='IncomeZhaohuo',
        ),
        migrations.AddField(
            model_name='payresult',
            name='IncomeAgent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='机器人佣金'),
        ),
        migrations.AddField(
            model_name='payresult',
            name='IncomeApp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='APP佣金'),
        ),
        migrations.AddField(
            model_name='payresult',
            name='IncomeJD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='京东佣金'),
        ),
        migrations.AddField(
            model_name='payresult',
            name='IncomeZhaohuo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='找货佣金'),
        ),
    ]
